# message type to describe the tracking information of the brick
# to be published as a topic
#
float64 position_x      # x coordinate
float64 position_y      # y coordinate
float64 position_z      # z coordinate
float64 orientation_x   # x of orientation quaternion
float64 orientation_y   # y of orientation quaternion
float64 orientation_z   # z of orientation quaternion
float64 orientation_w   # w of orientation quaternion
bool isDetected
bool flag
#uint8 sysmode
